name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl -sSfL https://github.com/rustwasm/wasm-pack/releases/download/v0.14.0/wasm-pack-v0.14.0-x86_64-unknown-linux-musl.tar.gz | tar xz -C /usr/local/bin --strip-components=1 wasm-pack-v0.14.0-x86_64-unknown-linux-musl/wasm-pack
      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Rust Cache
        uses: Swatinem/rust-cache@401aff9a7a08acb9d27b64936a90db81024cff97 # v2.8.2
      - name: Build
        run: |
          wasm-pack build --scope bitcoindevkit --target bundler --out-dir pkg-web --features "esplora"
          cd pkg-web
          jq '.name = "@bitcoindevkit/bdk-wallet-web"' package.json > temp.json && mv temp.json package.json
          cd ..
          wasm-pack build --scope bitcoindevkit --target nodejs --out-dir pkg-node --all-features
          cd pkg-node
          jq '.name = "@bitcoindevkit/bdk-wallet-node"' package.json > temp.json && mv temp.json package.json
          cd ..
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ./pkg-web
          key: ${{ github.sha }}-web
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ./pkg-node
          key: ${{ github.sha }}-node

  publish-npm-dry-run-web:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "lts/*"
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ./pkg-web
          key: ${{ github.sha }}-web
          fail-on-cache-miss: true
      - name: Dry Run Publish
        working-directory: pkg-web
        run: npm publish --dry-run

  publish-npm-dry-run-node:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "lts/*"
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ./pkg-node
          key: ${{ github.sha }}-node
          fail-on-cache-miss: true
      - name: Dry Run Publish
        working-directory: pkg-node
        run: npm publish --dry-run

  publish-npm:
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: [publish-npm-dry-run-web, publish-npm-dry-run-node]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ./pkg-web
          key: ${{ github.sha }}-web
          fail-on-cache-miss: true
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ./pkg-node
          key: ${{ github.sha }}-node
          fail-on-cache-miss: true
      - name: Publish web
        working-directory: pkg-web
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SKIP_PREPACK: true
      - name: Publish node
        working-directory: pkg-node
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SKIP_PREPACK: true
